build-patched-kao-kcmo-images.sh: get image name from brew container image metadata
crc-org/snc pull request #883
Opened 2024-05-15 09:49 UTC by redbeam

#871

2024-05-16 08:11 UTC, praveenkumar requested changes

2024-05-17 18:37 UTC, redbeam commented
/retest

2024-05-20 04:35 UTC, praveenkumar commented
/cherry-pick release-4.16

2024-05-20 04:35 UTC, praveenkumar commented
/cherry-pick master

2024-05-20 04:38 UTC, praveenkumar commented
@redbeam both commit  can be squashed to have a single one.

2024-05-20 17:01 UTC, redbeam commented on build-patched-kao-kcmo-images.sh
> +    rhel9_image_name=$(curl -L https://download.eng.bos.redhat.com/brewroot/packages/crc-cluster-kube-apiserver-operator-container/${version}/${release}/metadata.json | jq -r '.build.extra.image.inde
Yes, I was unsure about the variable name, so I just left it as it was.

I made the changes you suggested.

2024-05-20 17:08 UTC, redbeam commented
@praveenkumar Squashed.

2024-05-21 06:39 UTC, merged