Fix mirror URLs
crc-org/snc pull request #932
Opened 2024-07-03 14:18 UTC by redbeam

2024-07-05 09:25 UTC, gbraad commented
please use the commit and PR description to explain the change: what, and the reasoning: why

2024-07-07 21:59 UTC, redbeam commented
/retest

2024-07-08 15:08 UTC, redbeam commented
> please use the commit and PR description to explain the change: what, and the reasoning: why

Fixed - sorry about that. I opened this PR in a rush :D

2024-07-08 15:15 UTC, redbeam commented
/test e2e-microshift

2024-07-09 06:05 UTC, praveenkumar requested changes

2024-07-09 06:05 UTC, praveenkumar commented on microshift.sh
> +MIRROR=${MIRROR:-https://mirror.openshift.com/pub/openshift-v4/$ARCH/clients/ocp}
master branch is current dev for Openshift and MIRROR url for that is `ocp-dev-preview`

2024-07-09 06:05 UTC, praveenkumar commented on repos/mirror-microshift.repo
> +baseurl=https://mirror.openshift.com/pub/openshift-v4/$basearch/microshift/ocp/latest-4.16/el9/os/
here it should be change to https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp-dev-preview/latest-4.17/ one

2024-07-09 06:05 UTC, praveenkumar commented on ci_microshift.sh
> +./microshift.sh
This change shouldn't require because with prerelease flag we get the rpms from mirror.openshift.com

2024-07-09 06:05 UTC, praveenkumar commented on createdisk.sh
> +    ${YQ} eval --inplace ".ingress.listenAddress = null"  config.yaml
For master and release-4.17 this commit is not required because it is already fixed there.

2024-07-10 09:33 UTC, redbeam commented
/retest

2024-07-10 10:21 UTC, redbeam commented
/retest

2024-07-16 10:14 UTC, merged